[platformio]
src_dir = .

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Automatik detect port — uncomment dan isi jika tidak auto detect
; upload_port = /dev/ttyUSB0   ; Linux
; upload_port = COM3            ; Windows

upload_speed   = 921600
monitor_speed  = 115200

lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.5.0
